name: expense_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  fl_chart: ^1.0.0
  collection: ^1.17.2
  go_router: ^12.1.0
  flutter_hooks: ^0.20.3
  intl: ^0.18.1
  supabase_flutter: ^2.9.1
  get_it: ^8.0.3
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  flutter_launcher_icons: ^0.14.4
  super_tooltip: ^2.0.9
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/launcher/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Outfit-Light.ttf
          weight: 300
        - asset: assets/font/Outfit-Regular.ttf
          weight: 400
        - asset: assets/font/Outfit-Medium.ttf
          weight: 500
        - asset: assets/font/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/font/Outfit-Bold.ttf
          weight: 700
        - asset: assets/font/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Outfit-Black.ttf
          weight: 900
        
